version: '3'
services:
  front-end:
    build:
      context: .
      dockerfile: ./softy-pinko-front-end/Dockerfile
    image: softy-pinko-front-end:task5
    expose:
      - "9000"

  back-end:
    build:
      context: .
      dockerfile: ./softy-pinko-back-end/Dockerfile
    image: softy-pinko-back-end:task5
    expose:
      - "5252"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
